version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=src/videoask_handler/webhooks/routes.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
